---
- include_vars: vault

- name: Ensure group with same name as user exists
  group:
    name: "{{ sudo_user_name }}"
    state: present

- name: Ensure 'wheel' group exists
  group:
    name: wheel
    state: present

- name: Install sudo user
  user:
    name: "{{ sudo_user_name }}"
    groups: "{{ sudo_user_groups }}"
    home: "{{ sudo_user_homedir }}"
    password: "{{ sudo_user_password|password_hash('sha512') }}"
    shell: "{{ sudo_user_shell }}"
    state: present

- name: Add SSH key to authorized_keys
  authorized_key:
    user: "{{ sudo_user_name }}"
    key: "{{ lookup('file', '{{ sudo_user_ssh_pubkey }}') }}"
    manage_dir: yes
    state: present
